run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  enable:
    # Formatting and imports
    - gofmt
    - goimports

    # Bug detection
    - govet
    - staticcheck
    - errcheck
    - gosec

    # Code quality
    - unused
    - ineffassign
    - gosimple
    - misspell
    - unconvert
    - unparam
    - nakedret

    # Style and best practices
    - stylecheck
    - revive
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - gocognit

    # Error handling
    - errname
    - errorlint

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  errcheck:
    check-type-assertions: true
    check-blank: false

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude known false positives
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Allow unused parameters if they start with _
    - text: "parameter .* seems to be unused, consider removing or renaming it as _"
      linters:
        - revive

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
